name: Deploy docs

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    tags: [v*]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout # checkout
        uses: actions/checkout@v2

      - name: Setup hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.124.1'
          extended: true

      - name: Build
        run: npm install postcss-cli && hugo --minify

      - name: Setup aliyun oss
        run: wget http://gosspublic.alicdn.com/ossutil/1.7.18/ossutil64 && chmod +x ossutil64

      - name: Configure Alibaba Cloud OSSUTIL
        run: ./ossutil64 config -e oss-cn-hongkong.aliyuncs.com -i ${{ secrets.OSS_ACCESSKEYID }} -k ${{ secrets.OSS_ACCESSKEYSECRET }}

      - name: Determine release name
        id: release_name
        run: |
          if [[ "${GITHUB_REF}" == refs/heads/main ]]; then
            echo "BRANCH_NAME=latest" >> $GITHUB_ENV
          elif [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            TAG_NAME="${GITHUB_REF#refs/tags/}"
            echo "BRANCH_NAME=${TAG_NAME}" >> $GITHUB_ENV
          else
            echo "Error: Not on main branch or tag." >&2
            exit 1
          fi

      - name: Upload the web to the chosen oss bucket
        run: |
          echo "sub dir name: ${BRANCH_NAME}"
          ./ossutil64 cp -rf ./public/ oss://koupleless-dosc/${BRANCH_NAME}
